### PR TITLE
Support source builds on other OSs

### PR DESCRIPTION
**Pull request by pmaene**

### CODE REVIEW

**Comment by pmaene** [comment]
Small bump. Do we want to merge this, or do I close this PR?

**Comment by jovanbulck** [comment]
yes, good point! I think we should merge this (after confirming it doesn't break anything). I had a brief look at the code and it seems okay, but @muehlber maintains sancus-main. So maybe Tobias could have a look it doesn't break anything and merge?

**Comment by pmaene** [comment]
Sorry for bringing this up again, but do you happen to have had some time to look into this?

**Comment by jovanbulck** [comment]
thanks! I reviewed the changes and they look fine to me :+1:  Continuous integration should catch if something breaks on the main supported system (ubuntu)

**Comment by pmaene** [comment]
Awesome! Thanks a lot, @jovanbulck!

**Comment by jovanbulck** [comment]
hm your code broke the CI :/

https://travis-ci.org/github/sancus-pma/sancus-examples/builds/676583234

we should really integrate this into the PR flow for sancus-main --- waay too many makefiles and dependencies. At least the docker build should keep working, so I'll have to revert some of your stuff, esp tabs and the MSPGCC version it seems

**Comment by jovanbulck** [comment]
okay seems to be fixed now, not sure if the builds on other OSs still work, but the Ubuntu docker container goes fine now it seems ^^

**Comment by pmaene** [comment]
Shoot, sorry about that! I can't remember why I updated MSPGCC to a newer version, but I don't think it had anything to do with ESAT's CentOS install (which is the main reason I made these changes). Thanks for taking care of this!

**Comment by jovanbulck** [comment]
no worries :) Dependencies are tricky.. Also serves as a good reminder that we should look into better CI integration for the various repos at some point

**Comment by pmaene** [comment]
If I understood the correctly, the main issue are cross-repository triggers, right? I'm not sure if Travis has those out of the box, but might be possible to add a raw API call to trigger a build of a dependent repository. Not particularly clean, but you'd get a ping something broke downstream.

**Pull request merged**
